#  vim:ts=2:sts=2:sw=2:et
#
#  Author: Hari Sekhon
#  Date: 2016-12-09 22:13:19 +0000 (Fri, 09 Dec 2016)
#
#  https://github.com/harisekhon/Dockerfiles
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/harisekhon
#

version: '3'
services:
  hbase-master:
    image: hbase:2.3.3
    command: master
    hostname: hbase-master
    container_name: hbase-master
    depends_on:
      - zookeeper
    ports:
      - 16000:16000
      - 16010:16010
  hbase-regionserver:
    image: hbase:2.3.3
    command: regionserver
    hostname: hbase-regionserver
    container_name: hbase-regionserver
    depends_on:
      - zookeeper
    ports:
      - 16030:16030
      - 16201:16201
      - 16301:16301
  hbase-thrift:
    image: hbase:2.3.3
    command: thrift
    hostname: hbase-thrift
    container_name: hbase-thrift
    depends_on:
      - zookeeper
    ports:
      - 9090:9090
      - 9095:9095
  hbase-stargate:
    image: hbase:2.3.3
    command: stargate
    hostname: hbase-stargate
    container_name: hbase-stargate
    depends_on:
      - zookeeper
    ports:
      - 8080:8080
      - 8085:8085
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
